name: clima
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  geolocator: ^9.0.0
  http: ^0.13.4
  flutter_spinkit: ^5.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/

  fonts:
  - family: Spartan MB
    fonts:
    - asset: fonts/SpartanMB-Black.otf
      weight: 900

  - family: Bungee
    fonts:
    - asset: fonts/BungeeShade-Regular.ttf
      weight: 900

  - family: Monoton
    fonts:
    - asset: fonts/Monoton-Regular.ttf
      weight: 900

  - family: DiplomataSC
    fonts:
    - asset: fonts/DiplomataSC-Regular.ttf
      weight: 900

  - family: RubikWetPaint
    fonts:
    - asset: fonts/RubikWetPaint-Regular.ttf
      weight: 300

  - family: Neonderthaw
    fonts:
    - asset: fonts/Neonderthaw-Regular.ttf
      weight: 900

  - family: RubikWetPaints
    fonts:
    - asset: fonts/RubikWetPaint-Regular.ttf


